FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .

# Increase timeout to 1000 seconds to handle slow downloads
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.txt

COPY . .
# We use the port from env, defaulting to 8010
CMD uvicorn main:app --host 0.0.0.0 --port 8010