FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .

# Increase timeout to 1000 seconds to handle slow downloads
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.txt

COPY . .
# Streamlit configuration for reverse proxy
ENV STREAMLIT_SERVER_BASE_URL_PATH=/admin
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0
CMD ["streamlit", "run", "streamlit_app.py"]